#include <stdio.h>
#include <cuda_runtime.h>
#include <math.h>
#include <float.h>
#include <cuda_fp16.h>
#include <cuda_bf16.h>
#include <cuda_fp8.h>
#include <stdlib.h>
#include <algorithm>
#include <torch/extension.h>
#include <torch/types.h>
#include <vector>